---
- name: Create temporary log directory
  file:
    path: /opt/datadog-agent/logs
    state: directory
    recurse: true

- name: Pull Datadog agent image
  docker_image:
    name: '{{ datadog_agent_image }}'
    tag: '{{ datadog_agent_image_tag }}'

- name: Run Datadog agent container
  docker_container:
    env:
      DD_API_KEY: '{{ matic_dd_api_key }}'
      DD_LOGS_ENABLED: '{{ collect_logs }}'
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: '{{ collect_logs_all }}'
    image: '{{ datadog_agent_image }}:{{ datadog_agent_image_tag }}'
    memory: '{{ container_memory_limit | default(omit) }}'
    name: '{{ data_agent_container_name }}'
    restart_policy: '{{ agent_restart_policy }}'
    state: started
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /proc/:/host/proc:ro
    - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    - /opt/datadog-agent/logs:/opt/datadog-agent/run:rw